### ISSUE TITLE
runnable jar doesn't work in ubuntu/linux

### ISSUE THREAD

**Issue by leonardo-ono** [armin-reichert/pacman#1]
runnable jar (20180908) didn't work in ubuntu/linux openjdk 8.

but it works ok on windows.

**Comment by armin-reichert** [comment]
Thanks for testing! 

If you run the jar using the console window (java -jar pacman.jar) , do you see any exceptions?

**Comment by leonardo-ono** [comment]
sorry, i could only test now:

leo@leo:~/Downloads$ java -jar pacman.jar 
[2018-09-10 20:22:08:234] Clock frequency set to 60 Hz 
[2018-09-10 20:22:08:356] Application PacManApp created. 
[2018-09-10 20:22:09:088] Application shell created. 
[2018-09-10 20:22:09:263] Window-mode: 224x288 
[2018-09-10 20:22:09:391] Default view initialized. 
[2018-09-10 20:22:09:540] Pac-Man sprites extracted. 
java.lang.NegativeArraySizeException
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:450)
	at de.amr.easy.game.assets.AudioClip.<init>(AudioClip.java:31)
	at de.amr.easy.game.assets.Assets.sound(Assets.java:249)
	at de.amr.games.pacman.theme.ClassicPacManTheme.sound(ClassicPacManTheme.java:239)
	at de.amr.games.pacman.theme.ClassicPacManTheme.snd_die(ClassicPacManTheme.java:250)
	at de.amr.games.pacman.theme.ClassicPacManTheme.snd_allSounds(ClassicPacManTheme.java:244)
	at de.amr.games.pacman.theme.ClassicPacManTheme.<init>(ClassicPacManTheme.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at de.amr.games.pacman.theme.PacManThemes.use(PacManThemes.java:11)
	at de.amr.games.pacman.PacManApp.init(PacManApp.java:43)
	at de.amr.easy.game.Application.start(Application.java:163)
	at de.amr.easy.game.Application.lambda$0(Application.java:76)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[2018-09-10 20:22:09:857] Could not read sound resource from asset path: sfx/die.mp3 
java.lang.RuntimeException
	at de.amr.easy.game.assets.AudioClip.<init>(AudioClip.java:37)
	at de.amr.easy.game.assets.Assets.sound(Assets.java:249)
	at de.amr.games.pacman.theme.ClassicPacManTheme.sound(ClassicPacManTheme.java:239)
	at de.amr.games.pacman.theme.ClassicPacManTheme.snd_die(ClassicPacManTheme.java:250)
	at de.amr.games.pacman.theme.ClassicPacManTheme.snd_allSounds(ClassicPacManTheme.java:244)
	at de.amr.games.pacman.theme.ClassicPacManTheme.<init>(ClassicPacManTheme.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at de.amr.games.pacman.theme.PacManThemes.use(PacManThemes.java:11)
	at de.amr.games.pacman.PacManApp.init(PacManApp.java:43)
	at de.amr.easy.game.Application.start(Application.java:163)
	at de.amr.easy.game.Application.lambda$0(Application.java:76)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.RuntimeException: java.lang.RuntimeException
	at de.amr.easy.game.assets.Assets.sound(Assets.java:255)
	at de.amr.games.pacman.theme.ClassicPacManTheme.sound(ClassicPacManTheme.java:239)
	at de.amr.games.pacman.theme.ClassicPacManTheme.snd_die(ClassicPacManTheme.java:250)
	at de.amr.games.pacman.theme.ClassicPacManTheme.snd_allSounds(ClassicPacManTheme.java:244)
	at de.amr.games.pacman.theme.ClassicPacManTheme.<init>(ClassicPacManTheme.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at de.amr.games.pacman.theme.PacManThemes.use(PacManThemes.java:11)
	at de.amr.games.pacman.PacManApp.init(PacManApp.java:43)
	at de.amr.easy.game.Application.start(Application.java:163)
	at de.amr.easy.game.Application.lambda$0(Application.java:76)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException
	at de.amr.easy.game.assets.AudioClip.<init>(AudioClip.java:37)
	at de.amr.easy.game.assets.Assets.sound(Assets.java:249)
	... 27 more
[2018-09-10 20:22:09:860] Could not create Pac-Man theme for class 'ClassicPacManTheme 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.amr.games.pacman.actor.PacMan.lambda$1(PacMan.java:127)
	at java.util.Spliterators$IntArraySpliterator.forEachRemaining(Spliterators.java:1032)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at de.amr.games.pacman.actor.PacMan.createSprites(PacMan.java:127)
	at de.amr.games.pacman.actor.PacMan.<init>(PacMan.java:58)
	at de.amr.games.pacman.actor.Cast.<init>(Cast.java:40)
	at de.amr.games.pacman.controller.GameController.<init>(GameController.java:61)
	at de.amr.games.pacman.PacManApp.init(PacManApp.java:44)
	at de.amr.easy.game.Application.start(Application.java:163)
	at de.amr.easy.game.Application.lambda$0(Application.java:76)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by armin-reichert** [comment]
Problem seems to be a common one, see for example https://keithp.com/blogs/Java-Sound-on-Linux/

Added workaround that creates "no-op" audio clip if audio clip constructor throws an exception.

**Comment by leonardo-ono** [comment]
hello armin ! i tested the last release yesterday and apparently it's working now 👍

**Comment by leonardo-ono** [comment]
Hello Armin, sorry for the late reply ! The sound works ok in linux now, but it seems that it makes the game lag just a little. Indeed, the game is getting great ! I did not even know about the "cruise elroy" ^^'
